In [2]:
# creating numpy arrays:

In [5]:
# 1D np.array or vector
import numpy as np
a = np.array([1, 2, 3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
# 2D np.array or matrix
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print(type(b))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [7]:
# 3D np.array or tensor
c = np.array([[[1, 2], [4, 5]], [[7, 8], [10, 11]]])
print(c)
print(type(c))

[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]
<class 'numpy.ndarray'>


In [11]:
# data types in numpy arrays
d = np.array([1, 2, 3], dtype=float)
print(d)
print(type(d))

[1. 2. 3.]
<class 'numpy.ndarray'>


In [13]:
# np.arange()
a = np.arange(0, 10)
print(a)

b = np.arange(0, 10, 2)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [15]:
# with reshape() functon:
np.arange(0, 100, 10).reshape(2, 5) #first is rows and second is columns

array([[ 0, 10, 20, 30, 40],
       [50, 60, 70, 80, 90]])

In [16]:
# np.ones and np.zeros
np.ones((2, 3)) # 2 rows and 3 columns of ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.zeros((2, 3)) # 2 rows and 3 columns of zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# np.random
b = np.random.rand(3, 4) # 3 rows and 4 columns of random numbers between 0 and 1
print(b)

c = np.random.random((3, 4)) # 3 rows and 4 columns of random numbers between 0 and 1
print(c)


[[0.11827443 0.63992102 0.14335329 0.94466892]
 [0.52184832 0.41466194 0.26455561 0.77423369]
 [0.45615033 0.56843395 0.0187898  0.6176355 ]]
[[0.61209572 0.616934   0.94374808 0.6818203 ]
 [0.3595079  0.43703195 0.6976312  0.06022547]
 [0.66676672 0.67063787 0.21038256 0.1289263 ]]


In [23]:
# np.linspace()
a = np.linspace(0, 10, 5) # start, stop, number of points
print(a)

b = np.linspace(-10, 10, 10) # start, stop, number of points
print(b)

[ 0.   2.5  5.   7.5 10. ]
[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]


In [25]:
# np.identity()
np.identity(3) # 5x5 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])