Array Attributes:

In [6]:
import numpy as np
a1 = np.arange(10,dtype=np.int32)
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
a2 = np.arange(12,dtype=float).reshape(3,4)
print(a2)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [8]:
a3 = np.arange(8).reshape(2,2,2)
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [9]:
# ndim or no. of dimensions
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [10]:
# shape or no. of elements in each dimension
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [11]:
# size or total no. of elements in the array
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [12]:
# itemsize or size in bytes of each element in the array
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
8


In [13]:
# dtype or data type of the elements in the array
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


changing datatype:

In [14]:
a3.dtype

dtype('int64')

In [16]:
# astype() method to change the data type of the array
a3 = a3.astype(np.int32)
print(a3.dtype)

int32
