Array Operations:

In [2]:
import numpy as np
a1 = np.arange(12).reshape(3,4)
print(a1)

a2 = np.arange(12,24).reshape(3,4)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [4]:
# Scalar operation: Scalar operation in a NumPy array is the process of applying a single value (scalar) to every element of the array simultaneously.

# arithmetic operations: all arithmetic operations in NumPy are element-wise, meaning that they are applied to each element of the array independently. For example, if you add a scalar value to a NumPy array, it will be added to each element of the array. and all arithmetic operators (+, -, *, /, //, %, **) can be used for scalar operations in NumPy arrays.


In [5]:
a1 + 10

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [6]:
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [7]:
a1 / 3

array([[0.        , 0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        , 2.33333333],
       [2.66666667, 3.        , 3.33333333, 3.66666667]])

In [9]:
# relational operations:Relational operation in NumPy compares array elements with another array or a scalar and returns a Boolean (True or False) array.
a1 == 4

array([[False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False]])

In [10]:
a1 > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [12]:
# Vector Opertions : Vector operation in NumPy performs element-wise arithmetic between two arrays of the same shape.

# Vector arithmetic operations: Vector arithmetic operations in NumPy perform element-wise addition, subtraction, multiplication, and division between arrays.

In [13]:
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [14]:
a1 - a2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [15]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

Array Functions:

In [19]:
a1 = np.random.random((3,3))
print(a1)

a1 = np.round(a1*100)
print(a1)

[[0.27766449 0.06794572 0.56009705]
 [0.81972206 0.17286527 0.11926776]
 [0.50060338 0.80073234 0.66122638]]
[[28.  7. 56.]
 [82. 17. 12.]
 [50. 80. 66.]]


In [20]:
# max
np.max(a1)

np.float64(82.0)

In [31]:
# 0 -> column and 1 -> row
x = np.max(a1, axis=0)
print(x)

w = np.max(a1, axis=1)
print(w)

[82. 80. 66.]
[56. 82. 80.]


In [21]:
# min 
np.min(a1)

np.float64(7.0)

In [33]:
# 0 -> column and 1 -> row
x = np.min(a1, axis=0)
print(x)

w = np.min(a1, axis=1)
print(w)

[28.  7. 12.]
[ 7. 12. 50.]


In [22]:
# sum
np.sum(a1)

np.float64(398.0)

In [25]:
# product
np.prod(a1)

np.float64(48472123392000.0)

In [34]:
# mean
np.mean(a1)

np.float64(44.22222222222222)

In [35]:
# median 
np.median(a1)

np.float64(50.0)

In [36]:
# standard deviation
np.std(a1)

np.float64(27.45006690045593)

In [37]:
# variance
np.var(a1)

np.float64(753.5061728395062)

In [38]:
# trigonometric finctions : sin, cos, tan, arcsin, arccos, arctan
np.sin(a1)

array([[ 0.27090579,  0.6569866 , -0.521551  ],
       [ 0.31322878, -0.96139749, -0.53657292],
       [-0.26237485, -0.99388865, -0.02655115]])

In [43]:
# Dot product : Dot product in NumPy multiplies corresponding elements of two vectors or matrices and sums the results to produce a single value or a new matrix.

# A dot product is valid only when the number of columns in the first matrix equals the number of rows in the second matrix.

a2 = np.arange(12).reshape(3,4)
print(a2)

a3 = np.arange(12,24).reshape(4,3)
print(a3)

np.dot(a2,a3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [44]:
# log
np.log(a1)

array([[3.33220451, 1.94591015, 4.02535169],
       [4.40671925, 2.83321334, 2.48490665],
       [3.91202301, 4.38202663, 4.18965474]])

In [45]:
# exponential
np.exp(a1)

array([[1.44625706e+12, 1.09663316e+03, 2.09165950e+24],
       [4.09399696e+35, 2.41549528e+07, 1.62754791e+05],
       [5.18470553e+21, 5.54062238e+34, 4.60718663e+28]])

In [51]:
x = np.random.random((2,3))*100
print(x)

[[ 5.21970508 52.56216507 72.06559485]
 [70.72109771 66.67522137 82.95572272]]


In [52]:
# round
y = np.round(x)
print(y)

[[ 5. 53. 72.]
 [71. 67. 83.]]


In [54]:
z = np.floor(x)
print(z)

[[ 5. 52. 72.]
 [70. 66. 82.]]


In [55]:
v = np.ceil(x)
print(v)

[[ 6. 53. 73.]
 [71. 67. 83.]]
