indexing and slicing:

In [9]:
# Indexing:

In [2]:
import numpy as np
a1 = np.arange(10)
print(a1)

a2 = np.arange(12).reshape(3,4)
print(a2)

a3 = np.arange(8).reshape(2,2,2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [3]:
# find the last item from the array: through indexing 
print(a1[-1])
print(a1[0])

9
0


In [7]:
print(a2)

# fetch 6 from the array:
print(a2[1][2])
print(a2[1,2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
6


In [8]:
# fetch item from a 3D array:
print(a3)
print(a3[1][1][1])
print(a3[1,1,1])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
7
7


In [10]:
# Slicing:

In [11]:
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
# find 2,3,4 items from the array:
print(a1[2:5])

[2 3 4]


In [14]:
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [15]:
# fetech 1st row from a2:
print(a2[0,:])

[0 1 2 3]


In [17]:
# fetch 2nd column from a2:
print(a2[:,2])

[ 2  6 10]


In [21]:
# fetch 5,6 or 9,10 from a2:
print(a2[1:,1:3])

[[ 5  6]
 [ 9 10]]


In [22]:
# fetch 0,3,8,11 from a2:
print(a2[::2,::3])

[[ 0  3]
 [ 8 11]]


In [23]:
a4 = np.arange(27).reshape(3,3,3)
print(a4)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [26]:
"""
 fetch below matrix from a4:
 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]
"""
print(a4[1])

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [28]:
print(a4[::2])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [29]:
print(a4[0,1,:])

[3 4 5]


In [30]:
print(a4[1,:,1])

[10 13 16]


In [31]:
print(a4[2,1:,1:])

[[22 23]
 [25 26]]


In [33]:
print(a4[::2,0,::2])

[[ 0  2]
 [18 20]]


iterating:

In [39]:
print(a1)
for i in a1:
    print(i)

[0 1 2 3 4 5 6 7 8 9]
0
1
2
3
4
5
6
7
8
9


In [41]:
print(a2)

for i in a2:
    print(i)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [43]:
print(a4)

for i in a4:
    print(i)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [44]:
for i in np.nditer(a4):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


Reshaping:

In [47]:
# transpose of a2:
print(a2)
print(np.transpose(a2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [49]:
print(a2)
print(a2.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [52]:
# ravel
print(a2)
print(np.ravel(a2))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [53]:
print(a4)
print(a4.ravel())

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


Stacking:

In [55]:
# horizontal stack
aa = np.arange(12).reshape(3,4)
print (aa)

ab = np.arange(12,24).reshape(3,4)
print (ab)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [56]:
np.hstack((aa,ab))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [57]:
# vertical stack
np.vstack((aa,ab))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Splitting:

In [61]:
# horizontal spliting:
np.vsplit(aa,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [62]:
# vertical spliting:
np.vsplit(aa,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]