Numpy array vs Python list:

In [4]:
# speed view:
# NumPy is faster than Python lists because it stores data in contiguous memory and performs optimized vectorized operations using compiled C code.

In [5]:
# memeory or space view:
# Python lists consume more memory because they store references to objects rather than the actual values. In contrast, NumPy arrays store elements of the same data type in contiguous memory, making them much more memory-efficient. Additionally, NumPy allows you to control the size of each element using data types such as int8, int16, int32, and int64. By choosing a smaller data type when appropriate, you can further reduce memory usage and improve performance, especially when working with large datasets.

Advanced Indexing:

In [7]:
# fancy indexing:
import numpy as np
a = np.arange(24).reshape(6,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [8]:
a[[0,2,3]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [10]:
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [14]:
# Boolean Indexing:
a = np.random.randint(1,100,24).reshape(6,4)
print(a)

print(a>50)

[[21 48 50 34]
 [94 89 51  4]
 [35 75 20 98]
 [47 71 51 80]
 [89 51 59 30]
 [93 42  7 51]]
[[False False False False]
 [ True  True  True False]
 [False  True False  True]
 [False  True  True  True]
 [ True  True  True False]
 [ True False False  True]]


In [15]:
# find all numbers grater than 50:
a[a>50]

array([94, 89, 51, 75, 98, 71, 51, 80, 89, 51, 59, 93, 51], dtype=int32)

In [16]:
# find out even number in array:
a[a%2==0]

array([48, 50, 34, 94,  4, 20, 98, 80, 30, 42], dtype=int32)

In [18]:
# find all the numbers grater than 50 and even:
a[(a>50) & (a%2==0)]

array([94, 98, 80], dtype=int32)

In [19]:
# find all the numbers divisible by 7:
a[a%7==0]

array([21, 35, 98, 42,  7], dtype=int32)