In [1]:
# np.sort: np.sort() is a NumPy function that returns a new array with the elements sorted in ascending order along a specified axis, without modifying the original array.

In [4]:
import numpy as np

a = np.random.randint(1,100,15)
print(a)

b = np.random.randint(1,100,24).reshape(6,4)
print(b)

[15 57  6 87 77  4 44 47 17 48 36 50 18 25 13]
[[77  4 86 29]
 [10 14  3 50]
 [ 6 78 71 52]
 [87 42 79 12]
 [ 7 96 96 13]
 [99 21 56 77]]


In [6]:
# sorting a 1D array ascending order
np.sort(a)

array([ 4,  6, 13, 15, 17, 18, 25, 36, 44, 47, 48, 50, 57, 77, 87],
      dtype=int32)

In [7]:
# sorting a 1D array descending order
np.sort(a)[::-1]

array([87, 77, 57, 50, 48, 47, 44, 36, 25, 18, 17, 15, 13,  6,  4],
      dtype=int32)

In [ ]:
# sorting a 2D array ascending order and row wise:
np.sort(b)

array([[ 4, 29, 77, 86],
       [ 3, 10, 14, 50],
       [ 6, 52, 71, 78],
       [12, 42, 79, 87],
       [ 7, 13, 96, 96],
       [21, 56, 77, 99]], dtype=int32)

In [ ]:
# sorting a 2D array ascending order and row wise:
np.sort(b, axis=1)

array([[ 4, 29, 77, 86],
       [ 3, 10, 14, 50],
       [ 6, 52, 71, 78],
       [12, 42, 79, 87],
       [ 7, 13, 96, 96],
       [21, 56, 77, 99]], dtype=int32)

In [11]:
# sorting a 2D array ascending order and column wise:
np.sort(b, axis=0)

array([[ 6,  4,  3, 12],
       [ 7, 14, 56, 13],
       [10, 21, 71, 29],
       [77, 42, 79, 50],
       [87, 78, 86, 52],
       [99, 96, 96, 77]], dtype=int32)

In [12]:
# np.append: np.append() is a NumPy function that returns a new array with the elements of a appended to the end of the array along a given axis.

In [13]:
np.append(a, 100)

array([ 15,  57,   6,  87,  77,   4,  44,  47,  17,  48,  36,  50,  18,
        25,  13, 100])

In [16]:
np.append(b, [[94, 10, 11, 22]], axis=0)

array([[77,  4, 86, 29],
       [10, 14,  3, 50],
       [ 6, 78, 71, 52],
       [87, 42, 79, 12],
       [ 7, 96, 96, 13],
       [99, 21, 56, 77],
       [94, 10, 11, 22]])

In [18]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[77.,  4., 86., 29.,  1.],
       [10., 14.,  3., 50.,  1.],
       [ 6., 78., 71., 52.,  1.],
       [87., 42., 79., 12.,  1.],
       [ 7., 96., 96., 13.,  1.],
       [99., 21., 56., 77.,  1.]])

In [19]:
# np.concatenate: np.concatenate() is a NumPy function that returns a new array with the elements of two or more arrays concatenated along a specified axis.

In [20]:
c = np.arange(6).reshape(2,3)
print(c)

d = np.arange(6,12).reshape(2,3)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [21]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [23]:
# np.unique() is a function in NumPy that returns the sorted unique (non-duplicate) elements from an array.

In [24]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
np.unique(e)

array([1, 2, 3, 4, 5, 6])

In [26]:
f = np.array([[1,1,2,2,3,3,4,4,5,5,6,6],[1,1,2,2,3,3,4,4,5,5,6,6]])
np.unique(f)

array([1, 2, 3, 4, 5, 6])

In [28]:
# np.expand_dims() is a function in NumPy that adds a new axis (dimension) to an array at a specified position without changing its data.

In [33]:
print(a)
print(a.shape)

[15 57  6 87 77  4 44 47 17 48 36 50 18 25 13]
(15,)


In [35]:
x = np.expand_dims(a, axis=1)
print(x)
print(x.shape)

[[15]
 [57]
 [ 6]
 [87]
 [77]
 [ 4]
 [44]
 [47]
 [17]
 [48]
 [36]
 [50]
 [18]
 [25]
 [13]]
(15, 1)


In [36]:
y = np.expand_dims(a, axis=0)
print(y)
print(y.shape)

[[15 57  6 87 77  4 44 47 17 48 36 50 18 25 13]]
(1, 15)


In [37]:
# np.where() is a function in NumPy that returns elements or indices based on a condition, choosing values from one array or another.

In [38]:
a

array([15, 57,  6, 87, 77,  4, 44, 47, 17, 48, 36, 50, 18, 25, 13],
      dtype=int32)

In [39]:
# find all the indices from a where the value is greater than 50
np.where(a>50)

(array([1, 3, 4]),)

In [40]:
# replace all values greater than 50 with 0
np.where(a>50,0,a)

array([15,  0,  6,  0,  0,  4, 44, 47, 17, 48, 36, 50, 18, 25, 13],
      dtype=int32)