In [3]:
# np.argmax() is a function in NumPy that returns the index of the maximum element in an array along a specified axis.

In [5]:
import numpy as np

a = np.random.randint(1,100,15)
print(a)

b = np.random.randint(1,100,24).reshape(6,4)
print(b)

[ 4 52 85 39 13 26 47 39 18 60 55 31 28 25 53]
[[49 63 86 78]
 [90 46 64 20]
 [37 32 91 24]
 [57 31 60 81]
 [48 82 90 14]
 [43 14 40 30]]


In [6]:
np.argmax(a)

np.int64(2)

In [7]:
np.argmax(b)

np.int64(10)

In [8]:
np.argmax(b, axis=0)

array([1, 4, 2, 3])

In [9]:
np.argmax(b, axis=1)

array([2, 0, 2, 3, 2, 0])

In [10]:
# np.argmin() is a function in NumPy that returns the index of the minimum element in an array along a specified axis.

In [11]:
np.argmin(a)

np.int64(0)

In [12]:
np.argmin(b)

np.int64(19)

In [13]:
np.argmin(b, axis=0)

array([2, 5, 5, 4])

In [14]:
np.argmin(b, axis=1)

array([0, 3, 3, 1, 3, 1])

In [15]:
# np.cumsum() is a function in NumPy that returns the cumulative sum of array elements along a specified axis.

In [16]:
a

array([ 4, 52, 85, 39, 13, 26, 47, 39, 18, 60, 55, 31, 28, 25, 53],
      dtype=int32)

In [17]:
np.cumsum(a)

array([  4,  56, 141, 180, 193, 219, 266, 305, 323, 383, 438, 469, 497,
       522, 575])

In [18]:
b

array([[49, 63, 86, 78],
       [90, 46, 64, 20],
       [37, 32, 91, 24],
       [57, 31, 60, 81],
       [48, 82, 90, 14],
       [43, 14, 40, 30]], dtype=int32)

In [20]:
np.cumsum(b)

array([  49,  112,  198,  276,  366,  412,  476,  496,  533,  565,  656,
        680,  737,  768,  828,  909,  957, 1039, 1129, 1143, 1186, 1200,
       1240, 1270])

In [21]:
np.cumsum(b, axis=0)

array([[ 49,  63,  86,  78],
       [139, 109, 150,  98],
       [176, 141, 241, 122],
       [233, 172, 301, 203],
       [281, 254, 391, 217],
       [324, 268, 431, 247]])

In [22]:
np.cumsum(b, axis=1)

array([[ 49, 112, 198, 276],
       [ 90, 136, 200, 220],
       [ 37,  69, 160, 184],
       [ 57,  88, 148, 229],
       [ 48, 130, 220, 234],
       [ 43,  57,  97, 127]])

In [23]:
# np.cumprod() is a function in NumPy that returns the cumulative product of array elements along a specified axis.

In [24]:
a

array([ 4, 52, 85, 39, 13, 26, 47, 39, 18, 60, 55, 31, 28, 25, 53],
      dtype=int32)

In [25]:
np.cumprod(a)

array([                   4,                  208,                17680,
                     689520,              8963760,            233057760,
                10953714720,         427194874080,        7689507733440,
            461370464006400,    25375375520352000,   786636641130912000,
        3579081877955984384, -2756673419648148480,  1470261348324543488])

In [26]:
# np.percentile() is a function in NumPy that returns the value below which a given percentage of the data in an array falls.

In [27]:
a

array([ 4, 52, 85, 39, 13, 26, 47, 39, 18, 60, 55, 31, 28, 25, 53],
      dtype=int32)

In [28]:
np.percentile(a, 100)

np.float64(85.0)

In [29]:
np.percentile(a, 50)

np.float64(39.0)