In [2]:
# np.histogram() is a function in NumPy that computes the frequency distribution of array elements by grouping them into specified bins.

In [1]:
import numpy as np

a = np.random.randint(1,100,15)
print(a)

b = np.random.randint(1,100,24).reshape(6,4)
print(b)

[93 65 19 69 32 84  6 72 24 45 45 27 68 68 25]
[[56 83 89 21]
 [84 24 83 16]
 [91 36 34 36]
 [46 44 91 93]
 [22 85  1 26]
 [37 91 74 55]]


In [4]:
np.histogram(a,bins=[0,20,40,60,80,100])

(array([2, 4, 2, 5, 2]), array([  0,  20,  40,  60,  80, 100]))

In [5]:
np.histogram(b,bins=[0,20,40,60,80,100])

(array([2, 8, 4, 1, 9]), array([  0,  20,  40,  60,  80, 100]))

In [6]:
# np.corrcoef() is a function in NumPy that returns the correlation coefficient matrix, showing the strength and direction of the linear relationship between variables.

In [7]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

print(np.corrcoef(salary,experience))

[[1.         0.25344572]
 [0.25344572 1.        ]]


In [8]:
# np.isin() is a function in NumPy that returns a Boolean array indicating whether each element of an array is present in another array or list of values.

In [9]:
a

array([93, 65, 19, 69, 32, 84,  6, 72, 24, 45, 45, 27, 68, 68, 25],
      dtype=int32)

In [10]:
items = [10,20,30,40,50,60,70,80,90,100]

np.isin(a,items)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [11]:
a[np.isin(a,items)]

array([], dtype=int32)

In [12]:
# np.flip() is a function in NumPy that returns a copy of an array with the elements reversed along the given axis.


In [13]:
print(a)

np.flip(a)

[93 65 19 69 32 84  6 72 24 45 45 27 68 68 25]


array([25, 68, 68, 27, 45, 45, 24, 72,  6, 84, 32, 69, 19, 65, 93],
      dtype=int32)

In [14]:
print(b)

np.flip(b)

[[56 83 89 21]
 [84 24 83 16]
 [91 36 34 36]
 [46 44 91 93]
 [22 85  1 26]
 [37 91 74 55]]


array([[55, 74, 91, 37],
       [26,  1, 85, 22],
       [93, 91, 44, 46],
       [36, 34, 36, 91],
       [16, 83, 24, 84],
       [21, 89, 83, 56]], dtype=int32)

In [15]:
np.flip(b, axis=1)

array([[21, 89, 83, 56],
       [16, 83, 24, 84],
       [36, 34, 36, 91],
       [93, 91, 44, 46],
       [26,  1, 85, 22],
       [55, 74, 91, 37]], dtype=int32)

In [16]:
np.flip(b, axis=0)

array([[37, 91, 74, 55],
       [22, 85,  1, 26],
       [46, 44, 91, 93],
       [91, 36, 34, 36],
       [84, 24, 83, 16],
       [56, 83, 89, 21]], dtype=int32)

In [17]:
# np.put() is a function in NumPy that replaces elements at specified indices in an array with given values.

In [18]:
a

array([93, 65, 19, 69, 32, 84,  6, 72, 24, 45, 45, 27, 68, 68, 25],
      dtype=int32)

In [20]:
np.put(a,[0,1],[930,650])

print(a)

[930 650  19  69  32  84   6  72  24  45  45  27  68  68  25]


In [21]:
# np.delete() is a function in NumPy that returns a new array with specified elements removed from the input array.

In [22]:
np.delete(a,[0,1])

array([19, 69, 32, 84,  6, 72, 24, 45, 45, 27, 68, 68, 25], dtype=int32)

Set functions:

np.union1d

np.intersect1d

np.setdiff1d

np.setxor1d

np.in1d

In [23]:
# np.union1d():
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

print(np.union1d(a, b))

[1 2 3 4 5 6]


In [24]:
# np.intersect1d():
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

print(np.intersect1d(a, b))

[3 4]


In [25]:
# np.setdiff1d():
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

print(np.setdiff1d(a, b))

[1 2]


In [26]:
# np.setxor1d():
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

print(np.setxor1d(a, b))

[1 2 5 6]


In [29]:
# np.isin():
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

print(np.isin(a, b))

[False False  True  True]


In [30]:
# np.clip() is a function in NumPy that limits the values in an array to a specified minimum and maximum range, replacing values outside the range with the nearest boundary value.

array([1, 2, 3, 4])

In [33]:
aa = np.random.randint(1,100,15)
print(aa)

bb = np.random.randint(1,100,24).reshape(6,4)
print(bb)

[81 11 60 31 39 43 31  5 70 71 88 21 43 62 12]
[[98 53 64  9]
 [11 37 25 44]
 [86 20 26 49]
 [96 43 51 31]
 [26 56 55 12]
 [ 4 18 37 97]]


In [34]:
np.clip(aa,a_min=30, a_max=90)

array([81, 30, 60, 31, 39, 43, 31, 30, 70, 71, 88, 30, 43, 62, 30],
      dtype=int32)

In [35]:
# np.swapaxes() is a function in NumPy that returns a copy of an array with the axes swapped.

In [36]:
# np.uniform() is a function in NumPy that returns a random sample from a uniform distribution over a specified interval.

In [37]:
# np.count_nonzero() is a function in NumPy that returns the number of non-zero elements in an array.

In [38]:
# np.tile() is a function in NumPy that returns a new array by repeating the input array multiple times.

In [39]:
# np.repeat() is a function in NumPy that returns a new array by repeating the input array multiple times.

In [40]:
# np.allclose and equals()